// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY1huRJE1FiQaNFISB4zAvm-jHvjsXb-Y',
    appId: '1:34094062606:web:931785858ec6550a69705f',
    messagingSenderId: '34094062606',
    projectId: 'login1-446ba',
    authDomain: 'login1-446ba.firebaseapp.com',
    storageBucket: 'login1-446ba.appspot.com',
    measurementId: 'G-HXGDRWTVWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUzVwJlL-_4bmeMI3oyKOSjd-ROiXVH7g',
    appId: '1:34094062606:android:72991ca71baa783969705f',
    messagingSenderId: '34094062606',
    projectId: 'login1-446ba',
    storageBucket: 'login1-446ba.appspot.com',
  );
}
